### ISSUE TITLE
Publish docs on push

### ISSUE THREAD

**Issue by aaweaver-actuary** [aaweaver-actuary/predictables#32]
```

name: Sphinx Docs to gh-pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # or any required version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx your-package-name  # Replace with your package name

      - name: Build Documentation
        run: |
          cd docs  # Replace with your documentation directory if different
          sphinx-apidoc -o . ..  # Adjust arguments as needed
          make html  # or `sphinx-build -b html . _build/html`

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html  # Adjust to your build output directory

```
